Failing test: escaping inconsistent to requestInterceptor
For: https://github.com/swagger-api/swagger-js/issues/1220

`npm t` gives:
>  Error: Expected 'percent-twentyseven' to equal 'quote'

* Request has a quote (') in it
* The interceptor sees req.url ending in quote (') which is a perfectly valid thing for a URL to end in…
* However, the xmock  shows the actual URL ends in /%27